### ISSUE TITLE
Error On Installing Plugin

### ISSUE THREAD

**Issue by AncientAzem** [Sevii77/ffxiv_materialui_accent#1]
When I go to install the plugin and it tries to download all the files for the first time, I receive the following error:
![image](https://user-images.githubusercontent.com/10831565/141605966-ae7dd1f5-4de7-4773-a1be-b24e1734ecfa.png)

It appears to be a connection issue. Some of the files do download but after a while it just errors out.

**Comment by Sevii77** [comment]
It seems to be related to it downloading too many files at once, I've limited it to a maximum of 50 per second, please check if this has fixed the issue.

**Comment by AncientAzem** [comment]
Hmmm well it sometimes seems to give that error. After it crashes, the next launch will try and download some items, then when you press apply the following error is shown in the log:

![image](https://user-images.githubusercontent.com/10831565/141697844-9914e2d6-89c3-4b6d-a676-b27408e7aac5.png)

**Comment by Sevii77** [comment]
Try removing `%appdata%\XIVLauncher\pluginConfigs\MaterialUI`, my guess is that the download failed while downloading an option before, making it skip that on the next time it resumed downloading.
