### ISSUE TITLE
Unapply Dalamud Settings

### ISSUE THREAD

**Issue by bladehawkz** [Sevii77/ffxiv_materialui_accent#14]
Applying Material UI to dalamud windows seems somewhat difficult to revert ATM.
Maybe instead of having an application button, a checkbox (with unticking reverting any changes) be more appropriate?

**Comment by Sevii77** [comment]
It simply creates a style preset named Material UI in dalamud's Style Editor, and changes active style to it. To disable it go to `/xlsettings` > Look & Feel > Open Style Editor
