### ISSUE TITLE
False Goldsmith Icon

### ISSUE THREAD

**Issue by AstralDia** [Sevii77/ffxiv_materialui_accent#2]
The Goldsmith icon in the Default option for Job Icons - Content uses the glowing one instead.
![Goldsmith](https://user-images.githubusercontent.com/94688195/142618527-fb0c2ee4-2c6b-4c7d-b360-cdd123116803.jpg)

**Comment by Sevii77** [comment]
Seems like the dds icon file in MaterialUI itself is glow instead of default. https://github.com/skotlex/ffxiv-material-ui/tree/master/4K%20resolution/Black/Saved/UI/Icon/Icon/062011
