### ISSUE TITLE
Penumbra or this mod itself not applying to hotbars and HP/MP

### ISSUE THREAD

**Issue by ajindotpng** [Sevii77/ffxiv_materialui_accent#34]
The material UI is not being applied to hotbar skills/actions, inventory items, the HP/MP bars, and any sort of icon that can be put onto a hotbar, and I'm not sure why. I followed the install instructions and also relogged.

**Comment by imgidedin** [comment]
Are you clicking on Apply on /materialui or "Apply Dalamud Style"? You need to click Apply. Go to /penumbra, rediscover the mods (or /penumbra reload) and click on 'Installed mods' > Material UI and start selecting your configs from there.

**Comment by Sevii77** [comment]
The apply might've failed with those textures. Please check if `Material UI/Macro Gear Icon/Show/ui/uld/icona_frame_hr1.tex` exists in your Penumbra mod folder, if it doesn't try to reapply.
