### ISSUE TITLE
Job gauges don't get replaced

### ISSUE THREAD

**Issue by Braste** [Sevii77/ffxiv_materialui_accent#48]
As the title says, the job gauges do not get replaced. Tried it with Minimal Gauges V2 and Aetheris. The rest works fine. The files get replaced in the "effective changes" tab of penumbra, but no changed gauge
![image](https://user-images.githubusercontent.com/494984/151225194-dcc8f846-7cc4-48dc-b9f6-a94220f3da51.png)

**Comment by Sevii77** [comment]
Those job gauge textures only affect the simple gauges.

**Comment by Braste** [comment]
Well, maybe the text in the configuration window should be "Simple Gauges" instead of "Gauges" then,? Just an idea.

**Comment by Sevii77** [comment]
the HP and MP/GP/CP bars are also affected by this, and a simple version of these dont exist as they are 'simple' by default. Besides, the 'non simple' gauges are actually Job Gauges and not just Gauges.
