### ISSUE TITLE
Option to have default dialogbox styling

### ISSUE THREAD

**Issue by DenL** [Sevii77/ffxiv_materialui_accent#69]
Hello, would it be possible to add an option to disable styling for main dialogue box (all types)? Option to have game default dialog box instead of material ui styling. I found the sharp corners of the material ui dialog boxes to be a bit jarring.

Thanks!

**Comment by Sevii77** [comment]
Delete the file. Note: this will recreate itself when applying or auto updates. V2 will have a better way to disable files that are not wanted.
