### ISSUE TITLE
I don't have any options and show

### ISSUE THREAD

**Issue by AnyoneCn** [Sevii77/ffxiv_materialui_accent#7]
![3123123123](https://user-images.githubusercontent.com/86087425/147615874-e8b66370-a8a9-42d5-bd99-3c6475cbfce4.png)
I can't do anything, please help me

**Comment by Sevii77** [comment]
Please try disabling and reenabling the plugin. Also, the manual install isn't needed as the plugin will create its own.

**Comment by AnyoneCn** [comment]
oh no.I still can't
![31231231231](https://user-images.githubusercontent.com/86087425/147842914-1306a07d-0a53-42d8-917e-1197fe11d6fc.png)

**Comment by Sevii77** [comment]
I assume retry didn't fix it, please post your `%appdata%\XIVLauncher\dalamud.log`

**Comment by AnyoneCn** [comment]
[dalamud.log](https://github.com/Sevii77/ffxiv_materialui_accent/files/7797481/dalamud.log)
thx for ur help!

**Comment by Sevii77** [comment]
When it's trying to fetch `https://raw.githubusercontent.com/sevii77/ffxiv_materialui_accent/master/options.json` it fails with `The requested name is valid, but the requested type of data cannot be found` / `请求的名称有效，但是找不到请求的类型的数据`, which seems to be a DNS issue. Try changing your DNS server or using a vpn to see if that solves the issue.

**Comment by AnyoneCn** [comment]
i tried changing my DNS server or using a vpn...but nothing changed...no way, this is a limitation of the Chinese Internet..thank for ur help...
