### ISSUE TITLE
Material UI PvP Rank Gauges Wonky Looking

### ISSUE THREAD

**Issue by thakyZ** [Sevii77/ffxiv_materialui_accent#76]
So there is an issue with Material UI and the PvP rank gauges. I don't know if you specifically use the Material UI from the other GitHub repo that is normally used with TexTools. However, it has since been updated with a preliminary release for 6.1. The rank gauges should look like this:
![Normal looking job gauges with the Material UI for TexTools](https://user-images.githubusercontent.com/950594/164531034-29e78a2b-4d63-4b83-8b5a-5259f96a50b7.png)
However, they end up looking like this when I have the Material UI plugin enabled in Penumbra.
![Wonky looking job gauges with the Material UI for Dalamud](https://user-images.githubusercontent.com/950594/164531225-bc7bb1c8-c12c-4449-9c2a-991744197e8c.png)

**Comment by Sevii77** [comment]
fixed in 9d1ac0f9341ba8c6379f035f9032df6038db14e7
