### ISSUE TITLE
Since Material UI and Discord UI are discontinued by the original author, how will this plugin proceed?

### ISSUE THREAD

**Issue by frukbachers** [Sevii77/ffxiv_materialui_accent#81]

**Comment by Caliel666** [comment]
Material ui black is not discontinued, but besides that, this plugin will no longer be called material ui in the future due to the new update, whatever happens to material ui won't be related to us (never was), however, someone might continue updating that theme

**Comment by mekoichi** [comment]
I was able to replicate some of Skotlex's work (close enough) through mods and temporary patches during the big 6.0 update. With his consent, I'd be willing to fill in the gaps for any future updates once Skotlex discontinues the UI theme, and possibly create an off-shoot. 

I won't make any promises just yet as there's no official date for when the original theme will be discontinued.
