### ISSUE TITLE
Job icons reverting to vanilla randomly 

### ISSUE THREAD

**Issue by MistrxxGoat** [Sevii77/ffxiv_materialui_accent#84]
Some of my job icons will randomly revert to vanilla. I have swapped between all 4 of the penumbra options for jobs, and it continues to happen. [example pic](https://cdn.discordapp.com/attachments/926925288422653993/1008878034096496700/unknown.png)

**Comment by Sevii77** [comment]
Would be best to ask this on the Penumbra [Discord](https://discord.gg/kVva7DHV4r) or the [GitHub](https://github.com/xivdev/Penumbra), as all the MUI plugin does is create the Penumbra mod.
