### ISSUE TITLE
[6.2] Plugin not showing up in Dalamud

### ISSUE THREAD

**Issue by Kosba2** [Sevii77/ffxiv_materialui_accent#86]
Maybe I'm wrong, but I'm sure this has everything to do with 6.2 and no fault of your own:

Since the update and subsequent release of updated Dalamud, adding a Custom repository for this mod no longer adds it to the plugin list. 

I can't say for certain why as I didn't try to add this Plugin before the update, but I figured I'd at least get an Issue tracker going.

Pictures:
![image](https://user-images.githubusercontent.com/28957257/186539881-57f4b065-9559-424c-8c24-621d03bcf05a.png)
![image](https://user-images.githubusercontent.com/28957257/186539953-c9e5a616-ab4a-43c4-b4dc-57364184edd9.png)

**Comment by Sevii77** [comment]
Fixed in 68f352b269f1a978592e6de007089414d74f9b0f

**Comment by Kshumishyn** [comment]
Despite the new version, Dalamud is not adding it to the Plugin directory.

**Comment by Kosba2** [comment]
> Fixed in [68f352b](https://github.com/Sevii77/ffxiv_materialui_accent/commit/68f352b269f1a978592e6de007089414d74f9b0f)

Despite the new version, Dalamud is not adding it to the Plugin directory.

**Comment by Kosba2** [comment]
That did it, thanks for your prompt response and hard work!
