### ISSUE TITLE
[Feature Request] Connect to Github with system proxy.

### ISSUE THREAD

**Issue by maduser2021** [Sevii77/ffxiv_materialui_accent#88]
I'm living in Mainland China, it's a magic country with incomprehensible GFW and stupid ISP all that prevent me to connect to `api.github.com` and  `raw.githubusercontent.com`.

I love this mod, could we allow it to connect github with system proxy? Or some options that allow me to set up a proxy address manually.

Thank you :)

**Comment by Sevii77** [comment]
The current version is in maintance mode, no new features or changes will be made to it. The version thats being worked on won't have this issue as it won't be dependent on GitHub. I do know there's a fork for Chinese users which uses a proxy which might be of use.
