### ISSUE TITLE
Vanilla Dialog Boxes

### ISSUE THREAD

**Issue by myric227** [Sevii77/ffxiv_materialui_accent#89]
The main dialog box is still using the Material UI style when I have the Vanilla option select for Dialog.  The others such as, dragon, Ascian, etc, display correctly, it's only the main dialog box not using the setting from what I can tell.  I tested this through Textools, which I hate, to see if it works correctly, and it does.  I can download and import the Vanilla option as a separate mod in Penumbra, setting both it and Material UI to priority (), and it works as well.

**Comment by Sevii77** [comment]
Shnould be fixed now, might require manually Applying.
